Upgraded frequency-chain/api-augment to 0.9.29-rc1
LibertyDSNP/schemas pull request #12
Opened 2022-10-27 20:54 UTC by dopatraman

Problem
=======
The goal of this PR is to upgrade the `api-augment` package to the recent RC version.

2022-10-27 21:23 UTC, saraswatpuneet commented on package.json
> +    "@frequency-chain/api-augment": "0.9.29-rc1",
We should leave "^"

2022-10-27 22:00 UTC, saraswatpuneet approved these changes
One comment

2022-10-27 22:46 UTC, saraswatpuneet commented
@dopatraman  or @rlaferla can we also check and update name of extrinsic if it has changed after naming update.


https://github.com/LibertyDSNP/schemas/blob/84c5b99050e971093402c7ca4bfb5e08b5113956/deploy.ts#L86

2022-10-28 00:45 UTC, wilwade requested changes
I got a `TypeError: api.tx.schemas.registerSchema is not a function` when I tried to run it. I think we changed the name to createSchema right? Although not sure why it didn't fail on the ts build...

2022-10-28 16:05 UTC, dopatraman commented
@wilwade how did you run it? I ran both the build and the tests, both worked.

2022-10-28 16:08 UTC, wilwade commented
> @wilwade how did you run it? I ran both the build and the tests, both worked.

I ran the deploy against instant sealing: https://github.com/LibertyDSNP/schemas#deploy

2022-10-28 16:47 UTC, wilwade approved these changes

2022-10-28 18:35 UTC, merged