Rest of the Current DSNP Schemas
LibertyDSNP/schemas pull request #4
Opened 2022-08-15 13:17 UTC by wilwade

Problem
=======
Need to define the Frequency Schemas for the rest of the current DSNP Announcement Types

Part of https://github.com/LibertyDSNP/spec/issues/191

Solution
========

- Refactored the Parquet Tests to make them reusable
- Added the schemas for:
  - Update
  - Reply
  - Reaction
  - Tombstone
  - Profile

Steps to Verify:
----------------
1. Run the tests
1. Each announcement should match the spec here: https://spec.dsnp.org/DSNP/Announcements.html

2022-08-15 14:58 UTC, enddynayn approved these changes

2022-08-15 17:05 UTC, shannonwells requested changes
Everywhere there is an announcementType it's set to 16-bit width, but in the spec it's an Int32.

2022-08-15 17:05 UTC, shannonwells commented on dsnp/tombstone.ts
> +        bit_width: 16,
According to the spec this is an Int32

2022-08-15 17:05 UTC, shannonwells commented on dsnp/profile.ts
> +        bit_width: 16,
According to the spec this is Int32

2022-08-15 17:05 UTC, shannonwells commented on dsnp/reaction.ts
> +        bit_width: 16,
According to the spec this is Int32

2022-08-15 17:05 UTC, shannonwells commented on dsnp/tombstone.ts
> +        bit_width: 16,
According to the spec this is an Int32

2022-08-15 17:05 UTC, shannonwells commented on dsnp/update.ts
> +        bit_width: 16,
According to the spec this is an Int32

2022-08-16 12:08 UTC, saraswatpuneet approved these changes
Approval contingent on @shannonwells catch :dagger:

2022-08-16 12:36 UTC, wilwade commented on dsnp/tombstone.ts
> +        bit_width: 16,
Good catch. Updated them all.

2022-08-16 16:08 UTC, shannonwells approved these changes
Good to go with me

2022-08-16 16:24 UTC, merged